### ISSUE TITLE
Agregar algunos helpers para mejorar el código

### ISSUE THREAD

**Issue by lucasdc6** [Proyecto-de-Software/unlp-api-python#10]
Estaría bueno que los ejemplos con ORMs

- Pony
- SQLAlchemy

Entre los helpers, estaría bueno agregar filtrar los forms de las request

**Comment by lucasdc6** [comment]
Estaría bueno también agregar soporte para poder convertir a JSON los objetos de Pony y de SQLAlchemy.
Ya sea con un helper, o con un método que permita serializar a JSON esos objetos.

**Comment by VanzaA** [comment]
Ya agregue los filtros de parametros, falta solo el soporte para convertir a json

**Comment by fedeotaran** [comment]
Me gustan las propuestas

@VanzaA eso de los filtros de los parámetros es re del mundo Rails, pero reviso que tal queda. Creo que si no queda en el template igual sirve como ejemplo de una buena práctica que les podemos mostrar a los chicos.

@lucasdc6 me gusta lo de los ejemplos de pasar a json y posiblemente serializar para responder tambien. Hay librerías para eso. Creo que podemos buscar una para ver que tal queda como ejemplo. Y podemos hacer una guía de última. Esta es la única que conozco: https://marshmallow.readthedocs.io/en/stable/

**Comment by fedeotaran** [comment]
Los ejemplos los movismo, así que esta discución tal vez la podemos tener en el otro repo.
