### ISSUE TITLE
Carpeta resources

### ISSUE THREAD

**Issue by nicolasepiscopo** [Proyecto-de-Software/unlp-api-python#12]
Buenas, 

Carpeta `resources`. 

Como lo establece el `README.md` es un `Módulo con los controladores de la aplicación (parte web)`.

Por lo que he visto al trabajar con proyectos hechos en Flask a esa carpeta no se la suele llamar de esa forma, en cambio se usa el termino `views` que tiene más sentido ya que son los archivos encargados de renderizar los templates.

Quizá `resources` tendría mas sentido si se usaran `annotations` para las rutas en vez de definirlas en el archivo principal donde se crea la aplicación.

Saludos!

**Comment by fedeotaran** [comment]
Creo que `views` es un concepto más de Django.

En este módulo también está el apartado de `/api` en donde ahí no renderiza templates.

Si les ponemos `views` tengo miedo que se confunda con la parte de `view` de MVC cuando en realidad este módulo tiene los controladores.

Creo en todo caso que `controllers`, como lo solíamos llamarlo, sería un reemplazo válido.

`resources` me parece un buen nombre dado que representa la capa que tiene la lógica donde se exponen los **recursos** ya sea con una respuesta json y con una respuesta html.

Fácilmente podría ser reemplazada la forma que enlazamos las funciones con la ruta con [`blueprints`](https://flask.palletsprojects.com/en/1.1.x/blueprints/) en los resources/contraladores y usando `decorators`, como mensionas, dentro de esos archivos. Esto no lo hicimos en el ejemplo base así (aunque tal vez sería lo más prolijo), porque creemos que tal vez es sumarle mucho a alumnos que tal vez no conocieron Python hasta llegar a esta materia.

Gracias Nico, lo tendremos en cuenta.

¡Saludos!

**Comment by matiaspagano** [comment]
Lo de blueprints  me parece sumarle demasiado a los chicos.
