### ISSUE TITLE
Configuración de variables de entorno

### ISSUE THREAD

**Issue by JulianPasquale** [Proyecto-de-Software/unlp-api-python#13]
Hola, vengo a plantear una discusión sobre las variables de configuración de la app.

Más allá de que ahora se encuentran localizadas en un solo archivo y todo prolijo, la problemática que encuentro es que este archivo está versionado, por lo que los alumnos van a tener que cambiar las credenciales y/o nombre de su base de datos local cada vez que hagan un pull si otro de sus compañeros tiene sus valores distintos.
Es decir, la estructura actual va a provocar que ante cada commit de otro compañero tengan que cambiar esta configuración, o bien se pongan de acuerdo y se creen todos un usuario con el mismo nombre y pass para su MySQL local, pero de todas formas en el código van a estar sus credenciales.

Hablando con @fedeotaran sobre el tema, decidimos traerlo a debate acá.
Subí [ésta rama](https://github.com/Proyecto-de-Software/unlp-api-python/tree/feature/config_from_envfiles) con una aproximación a la solución que planteo.
Utilicé la librería [python-dotenv](https://pypi.org/project/python-dotenv/) para poder levantar las variables de un archivo distinto dependiendo el entorno de la aplicación y de esta forma poder controlar variables como `DEBUG` por ejemplo, cuyo valor claramente varía para producción y desarrollo. Es una pequeña vueltita más a lo que plantea la [documentación de Flask](https://flask.palletsprojects.com/en/1.1.x/cli/#environment-variables-from-dotenv) sobre utilizar un solo archivo `.env`.

También me surgió la duda sobre las configuraciones que se van a necesitar para ejecutar esto en el server de la cátedra. El año pasado los ayudantes le pasaban las credenciales a los alumnos, quienes debían versionar valores como las credenciales de la base de datos (lo cual entiendo que no es tan crítico porque solo era accesible para conectarse dentro de la misma red).
La pregunta en concreto es: ¿Las configuraciones van a tener que hacerse nuevamente de esta forma o ya van a tener estos valores configurados? Creo que @matiaspagano me va a poder contestar.
En el ejemplo de la rama que mencioné anteriormente, el archivo con las variables de producción no lo ignore más que nada por esto último.

**Comment by matiaspagano** [comment]
Que largo!

Lo ideal para mi sería que levanten variables de entorno. En el servidor cada grupo tiene un virtualenv separado,  podría agregar que cada grupo genere archivo .env cada vez que se sincroniza o generar los 90 .envs con ansible y solo copiarlas al home de cada uno. 
Nos falta un orquestador para poder tener todo configurable por interfaz! 
Tenemos que tenes en claro exactamente que variables van a usar todos, seguro la conexión a la base, pero por ahi surge alguna más. 

La otra opción muuuucho más cabeza es que levanten variables de entorno y si no existen dejen las de producción por defecto cosa de que cada vez que suban funcione y localmente usen cada uno sus variables.
Dije mucho más cabeza, se versionan las credenciales de base de datos, que funcionan localmente o por phpmyadmin, o sea, cualquiera puede borrar la base en "prod" de cualquier grupo con un poco de maldad.

**Comment by fedeotaran** [comment]
Para mí se debería agregar tanto en la config de [Dev](https://github.com/Proyecto-de-Software/unlp-api-python/blob/58f80cfd2888a78e189952e7027f8a36634cbba0/config.py#L20) como de [Prod](https://github.com/Proyecto-de-Software/unlp-api-python/blob/58f80cfd2888a78e189952e7027f8a36634cbba0/config.py#L43) que los valores esos se sacan de variables de entorno con `os.getenv("VAR")`. Con eso es mas que suficiente para cubrir el deploy y que no se pisen los valores entre los desarrolladores.

Además guardaría [este enlace](https://flask.palletsprojects.com/en/1.1.x/cli/#environment-variables-from-dotenv) para dejarlo como una recomendación en alguna guía o mensionarlo en una consulta práctica, pero no lo sumaría al template. Que lo hagan ellos, guiados por los ayudantes.

**Comment by fedeotaran** [comment]
A menos de que Mati necesite sí o sí el archivo `.env` para que se levanten esas variables de entorno por grupo. Ahí medio que no nos queda otra que usar la lib o que como dijo Matias hacer que tomen los valores de prod fijos si la variable de entorno no está.

**Comment by matiaspagano** [comment]
El tema es ese, todos los grupos funcionan en el mismo servidor, salvo que las pueda agregar en el virtualhost, o en el virtualenv. Se puede setear variables de ambiente exclusivas de un virtualenv? Tipo [direnv](https://direnv.net/) para los directorios.

**Comment by fedeotaran** [comment]
Si necesitas eso, las alternativas son 2:
- Se usa `direnv` en el servidor y vos agregas las variables de entrono y los alumnos lo usan como quieran.
- Los alumnos usan `python-dotenv` como dijo Juli y en el servidor no se toca nada. Para esta opción dependemos un poco de los alumnos, necesitamos que tengan la lib al menos en un `requirements.txt` (parece algo sensillo pero en Python nos pasa que no agregan ahí las libs que usan).

**Comment by matiaspagano** [comment]
direnv en el servidor nunca lo separe teniendo 90 juntos y teniendo un servidor web que lo instancia, no es que estas en una "carpeta", hay que investigar, lo del requirements esta bien que lo hagan, como el año pasado.

**Comment by JulianPasquale** [comment]
Creo que no es necesario el uso de `direnv`. Si les podemos definir un `.env` en la carpeta de cada grupo con las credenciales, para mi va a alcanzar.
Ellos van a poder tener un `.env.production` versionado donde puedan agregar mas variables, claramente sin sobrescribir las credenciales porque no les va a andar. Con este esquema ya no me parece tan critico que no se ignore este archivo de variables de produccion, porque no va a tener credenciales de ningún tipo al menos por ahora y les da la flexibilidad a ellos de crear variables nuevas sin tener que pedirnos a nosotros que la agreguemos.

**Comment by fedeotaran** [comment]
Ya lo hablamos con @JulianPasquale va a hacer un PR y con los cambios para usar variables de entorno y en caso de no estar seteadas las de prod le vamos a decir que versionen las del grupo. Hace el PR y lo manda.
